-- =============================================================================
-- Clouds Platform Consolidated Database Migration
-- Complete schema for migrating to a new Supabase project
-- Tables use clouds_ prefix for multi-project compatibility
-- =============================================================================
-- Run this entire script in your new Supabase project's SQL Editor
-- All tables use RLS with permissive policies for anon key access
-- =============================================================================

-- =============================================================================
-- 1. AUTH_TOKENS TABLE
-- Stores DiceCloud authentication tokens for cross-session persistence
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.auth_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL UNIQUE,
    dicecloud_token TEXT NOT NULL,
    username VARCHAR(255) DEFAULT 'DiceCloud User',
    user_id_dicecloud VARCHAR(255),
    token_expires TIMESTAMP WITH TIME ZONE,
    discord_user_id VARCHAR(255),
    discord_username VARCHAR(255),
    discord_global_name VARCHAR(255),
    browser_info JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    -- Session tracking fields
    session_id TEXT,
    last_seen TIMESTAMPTZ,
    -- Session invalidation fields
    invalidated_at TIMESTAMPTZ,
    invalidated_by_session TEXT,
    invalidated_reason VARCHAR(100),
    -- Multi-app support
    apps TEXT[] DEFAULT '{}',
    owlbear_player_id TEXT
);

-- Indexes for auth_tokens
CREATE INDEX IF NOT EXISTS idx_auth_tokens_user_id ON public.auth_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_auth_tokens_updated_at ON public.auth_tokens(updated_at);
CREATE INDEX IF NOT EXISTS idx_auth_tokens_discord_user_id ON public.auth_tokens(discord_user_id);
CREATE INDEX IF NOT EXISTS idx_auth_tokens_session_id ON public.auth_tokens(session_id);
CREATE INDEX IF NOT EXISTS idx_auth_tokens_last_seen ON public.auth_tokens(last_seen);
CREATE INDEX IF NOT EXISTS idx_auth_tokens_owlbear_player_id ON public.auth_tokens(owlbear_player_id);

-- Unique constraint on user_id + session_id
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name = 'auth_tokens' AND constraint_name = 'unique_user_session'
    ) THEN
        ALTER TABLE public.auth_tokens ADD CONSTRAINT unique_user_session UNIQUE (user_id, session_id);
    END IF;
END $$;

-- Comments for auth_tokens
COMMENT ON TABLE public.auth_tokens IS 'Stores DiceCloud authentication tokens for cross-session persistence';
COMMENT ON COLUMN public.auth_tokens.user_id IS 'Browser fingerprint-based user identifier';
COMMENT ON COLUMN public.auth_tokens.dicecloud_token IS 'DiceCloud authentication token';
COMMENT ON COLUMN public.auth_tokens.username IS 'DiceCloud username';
COMMENT ON COLUMN public.auth_tokens.user_id_dicecloud IS 'DiceCloud user ID';
COMMENT ON COLUMN public.auth_tokens.token_expires IS 'Token expiration timestamp';
COMMENT ON COLUMN public.auth_tokens.discord_user_id IS 'Discord user ID (linked account)';
COMMENT ON COLUMN public.auth_tokens.discord_username IS 'Discord username (linked account)';
COMMENT ON COLUMN public.auth_tokens.discord_global_name IS 'Discord global name (display name)';
COMMENT ON COLUMN public.auth_tokens.browser_info IS 'Browser metadata for debugging';
COMMENT ON COLUMN public.auth_tokens.session_id IS 'Unique identifier for each browser session';
COMMENT ON COLUMN public.auth_tokens.last_seen IS 'Timestamp when this session was last active';
COMMENT ON COLUMN public.auth_tokens.apps IS 'Array of apps the user has connected: rollcloud, owlcloud, foundcloud, etc.';
COMMENT ON COLUMN public.auth_tokens.owlbear_player_id IS 'Owlbear Rodeo player ID for this user, used by OwlCloud';

-- RLS for auth_tokens
ALTER TABLE public.auth_tokens ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own tokens" ON public.auth_tokens
    FOR SELECT USING (true);

CREATE POLICY "Users can insert own tokens" ON public.auth_tokens
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Users can update own tokens" ON public.auth_tokens
    FOR UPDATE USING (true);

CREATE POLICY "Users can delete own tokens" ON public.auth_tokens
    FOR DELETE USING (true);

-- Grant permissions for auth_tokens
GRANT ALL ON public.auth_tokens TO anon;
GRANT ALL ON public.auth_tokens TO authenticated;

-- =============================================================================
-- 2. CLOUDS_PAIRINGS TABLE
-- Links DiceCloud users to Discord webhooks via short pairing codes
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.clouds_pairings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pairing_code VARCHAR(6) NOT NULL UNIQUE,
  dicecloud_user_id VARCHAR(50),
  dicecloud_username VARCHAR(100),
  discord_guild_id VARCHAR(20),
  discord_guild_name VARCHAR(100),
  discord_channel_id VARCHAR(20),
  discord_channel_name VARCHAR(100),
  discord_user_id VARCHAR(20),
  discord_username VARCHAR(100),
  discord_global_name VARCHAR(100),
  webhook_url TEXT,
  status VARCHAR(20) DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  connected_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '30 minutes'),
  last_activity TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for clouds_pairings
CREATE INDEX IF NOT EXISTS idx_pairing_code ON public.clouds_pairings(pairing_code);
CREATE INDEX IF NOT EXISTS idx_dicecloud_user ON public.clouds_pairings(dicecloud_user_id);
CREATE INDEX IF NOT EXISTS idx_discord_guild ON public.clouds_pairings(discord_guild_id);

-- RLS for clouds_pairings
ALTER TABLE public.clouds_pairings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anonymous read pairings" ON public.clouds_pairings
  FOR SELECT USING (true);

CREATE POLICY "Allow anonymous insert pairings" ON public.clouds_pairings
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow anonymous update pairings" ON public.clouds_pairings
  FOR UPDATE USING (true);

-- Grant permissions for clouds_pairings
GRANT ALL ON public.clouds_pairings TO anon;
GRANT ALL ON public.clouds_pairings TO authenticated;

-- =============================================================================
-- 3. CLOUDS_CHARACTERS TABLE
-- Stores character data for cloud sync and Discord bot integration
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.clouds_characters (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id_dicecloud VARCHAR(255) NOT NULL,
    dicecloud_character_id VARCHAR(255) NOT NULL,
    character_name VARCHAR(255) NOT NULL,
    race VARCHAR(100),
    class VARCHAR(100),
    level INTEGER DEFAULT 1,
    alignment VARCHAR(50),
    hit_points JSONB,
    hit_dice JSONB,
    temporary_hp INTEGER DEFAULT 0,
    death_saves JSONB,
    inspiration BOOLEAN DEFAULT false,
    armor_class INTEGER DEFAULT 10,
    speed INTEGER DEFAULT 30,
    initiative INTEGER DEFAULT 0,
    proficiency_bonus INTEGER DEFAULT 2,
    attributes JSONB,
    attribute_mods JSONB,
    saves JSONB,
    skills JSONB,
    spell_slots JSONB,
    resources JSONB,
    conditions JSONB,
    raw_dicecloud_data JSONB,
    pairing_id UUID REFERENCES public.clouds_pairings(id) ON DELETE SET NULL,
    discord_user_id VARCHAR(255),
    owlbear_player_id TEXT,
    is_active BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for clouds_characters
CREATE INDEX IF NOT EXISTS idx_clouds_characters_user_id_dicecloud ON public.clouds_characters(user_id_dicecloud);
CREATE INDEX IF NOT EXISTS idx_clouds_characters_dicecloud_character_id ON public.clouds_characters(dicecloud_character_id);
CREATE INDEX IF NOT EXISTS idx_clouds_characters_discord_user_id ON public.clouds_characters(discord_user_id);
CREATE INDEX IF NOT EXISTS idx_clouds_characters_pairing_id ON public.clouds_characters(pairing_id);
CREATE INDEX IF NOT EXISTS idx_clouds_characters_owlbear_player_id ON public.clouds_characters(owlbear_player_id);
CREATE INDEX IF NOT EXISTS idx_clouds_characters_updated_at ON public.clouds_characters(updated_at);

-- Unique constraint: one character ID per user
CREATE UNIQUE INDEX IF NOT EXISTS idx_clouds_characters_unique_char
ON public.clouds_characters(user_id_dicecloud, dicecloud_character_id);

-- Comments for clouds_characters
COMMENT ON TABLE public.clouds_characters IS 'Stores character data for cloud sync and Discord bot integration';
COMMENT ON COLUMN public.clouds_characters.id IS 'Primary key for character record';
COMMENT ON COLUMN public.clouds_characters.user_id_dicecloud IS 'DiceCloud user ID (Meteor ID) for character ownership';
COMMENT ON COLUMN public.clouds_characters.dicecloud_character_id IS 'DiceCloud character ID for reference';
COMMENT ON COLUMN public.clouds_characters.raw_dicecloud_data IS 'Full raw data from DiceCloud API for debugging and fallback';
COMMENT ON COLUMN public.clouds_characters.owlbear_player_id IS 'Owlbear Rodeo player ID for linking characters to Owlbear sessions';
COMMENT ON COLUMN public.clouds_characters.is_active IS 'Whether this character is the active character for this user';

-- RLS for clouds_characters
ALTER TABLE public.clouds_characters ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for anon key" ON public.clouds_characters
    FOR SELECT USING (true);

CREATE POLICY "Enable insert for anon key" ON public.clouds_characters
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for anon key" ON public.clouds_characters
    FOR UPDATE USING (true);

CREATE POLICY "Enable delete for anon key" ON public.clouds_characters
    FOR DELETE USING (true);

CREATE POLICY "Service role full access" ON public.clouds_characters
    FOR ALL USING (
        auth.jwt() ->> 'role' = 'service_role'
    );

-- Grant permissions for clouds_characters
GRANT ALL ON public.clouds_characters TO anon;
GRANT ALL ON public.clouds_characters TO authenticated;

-- =============================================================================
-- 4. CLOUDS_COMMANDS TABLE
-- Enables Discord → Extension communication (button clicks, etc.)
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.clouds_commands (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pairing_id UUID REFERENCES public.clouds_pairings(id) ON DELETE CASCADE,
  discord_user_id VARCHAR(20) NOT NULL,
  discord_username VARCHAR(100),
  discord_message_id VARCHAR(20),
  command_type VARCHAR(50) NOT NULL,
  command_data JSONB DEFAULT '{}',
  character_name VARCHAR(100),
  action_name VARCHAR(200),
  status VARCHAR(20) DEFAULT 'pending',
  result JSONB DEFAULT NULL,
  error_message TEXT DEFAULT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  processed_at TIMESTAMPTZ DEFAULT NULL,
  expires_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '5 minutes'),
  timeout_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '30 seconds')
);

-- Indexes for clouds_commands
CREATE INDEX IF NOT EXISTS idx_commands_pending
  ON public.clouds_commands(pairing_id, status, created_at)
  WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS idx_commands_message
  ON public.clouds_commands(discord_message_id);

CREATE INDEX IF NOT EXISTS idx_commands_discord_user
  ON public.clouds_commands(discord_user_id);

-- RLS for clouds_commands
ALTER TABLE public.clouds_commands ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anonymous read commands" ON public.clouds_commands
  FOR SELECT USING (true);

CREATE POLICY "Allow anonymous insert commands" ON public.clouds_commands
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow anonymous update commands" ON public.clouds_commands
  FOR UPDATE USING (true);

-- Grant permissions for clouds_commands
GRANT ALL ON public.clouds_commands TO anon;
GRANT ALL ON public.clouds_commands TO authenticated;

-- =============================================================================
-- 5. CLOUDS_TURNS TABLE
-- Extension writes turn data here, Pip Bot posts to Discord with buttons
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.clouds_turns (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pairing_id UUID REFERENCES public.clouds_pairings(id) ON DELETE CASCADE,
  event_type VARCHAR(30) NOT NULL,
  character_name VARCHAR(100),
  character_id VARCHAR(50),
  round_number INTEGER,
  initiative INTEGER,
  action_available BOOLEAN DEFAULT true,
  bonus_available BOOLEAN DEFAULT true,
  movement_available BOOLEAN DEFAULT true,
  reaction_available BOOLEAN DEFAULT true,
  available_actions JSONB DEFAULT '[]',
  status VARCHAR(20) DEFAULT 'pending',
  discord_message_id VARCHAR(20),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  posted_at TIMESTAMPTZ DEFAULT NULL,
  expires_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '1 minute')
);

-- Indexes for clouds_turns
CREATE INDEX IF NOT EXISTS idx_turns_pending
  ON public.clouds_turns(pairing_id, status, created_at)
  WHERE status = 'pending';

-- RLS for clouds_turns
ALTER TABLE public.clouds_turns ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anonymous read turns" ON public.clouds_turns
  FOR SELECT USING (true);

CREATE POLICY "Allow anonymous insert turns" ON public.clouds_turns
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow anonymous update turns" ON public.clouds_turns
  FOR UPDATE USING (true);

-- Grant permissions for clouds_turns
GRANT ALL ON public.clouds_turns TO anon;
GRANT ALL ON public.clouds_turns TO authenticated;

-- =============================================================================
-- 6. PIP2_INSTANCES TABLE
-- Manages user Pip 2 Discord bot instances
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.pip2_instances (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  discord_user_id TEXT NOT NULL,
  guild_id TEXT NOT NULL,
  guild_name TEXT NOT NULL DEFAULT 'Unknown Server',
  channel_id TEXT NOT NULL,
  channel_name TEXT NOT NULL DEFAULT 'unknown',
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for pip2_instances
CREATE INDEX IF NOT EXISTS idx_pip2_instances_discord_user
  ON public.pip2_instances(discord_user_id);

CREATE INDEX IF NOT EXISTS idx_pip2_instances_guild
  ON public.pip2_instances(guild_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_pip2_instances_unique_channel
  ON public.pip2_instances(guild_id, channel_id);

-- RLS for pip2_instances
ALTER TABLE public.pip2_instances ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own instances" ON public.pip2_instances
  FOR SELECT USING (true);

CREATE POLICY "Users can create instances" ON public.pip2_instances
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Users can update their own instances" ON public.pip2_instances
  FOR UPDATE USING (true);

CREATE POLICY "Users can delete their own instances" ON public.pip2_instances
  FOR DELETE USING (true);

-- Grant permissions for pip2_instances
GRANT ALL ON public.pip2_instances TO anon;
GRANT ALL ON public.pip2_instances TO authenticated;

-- =============================================================================
-- 7. GUILD_COMMAND_CONFIG TABLE
-- Stores guild-specific command configurations for Pip2
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.guild_command_config (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  guild_id TEXT NOT NULL UNIQUE,
  guild_name TEXT,
  config JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for guild_command_config
CREATE INDEX IF NOT EXISTS idx_guild_command_config_guild_id
  ON public.guild_command_config(guild_id);

-- RLS for guild_command_config
ALTER TABLE public.guild_command_config ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view guild configs" ON public.guild_command_config
  FOR SELECT USING (true);

CREATE POLICY "Users can create guild configs" ON public.guild_command_config
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Users can update guild configs" ON public.guild_command_config
  FOR UPDATE USING (true);

CREATE POLICY "Users can delete guild configs" ON public.guild_command_config
  FOR DELETE USING (true);

-- Grant permissions for guild_command_config
GRANT ALL ON public.guild_command_config TO anon;
GRANT ALL ON public.guild_command_config TO authenticated;

-- =============================================================================
-- 8. STORAGE BUCKET
-- Create bucket for token images
-- =============================================================================

-- Note: Run this separately in the Supabase Storage UI or via Storage API
-- INSERT INTO storage.buckets (id, name, public)
-- VALUES ('clouds-assets', 'clouds-assets', true);

-- =============================================================================
-- 9. HELPER FUNCTIONS
-- =============================================================================

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Function to update pip2_instances updated_at
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Cleanup function for expired pairings
CREATE OR REPLACE FUNCTION public.cleanup_expired_pairings()
RETURNS void AS $$
BEGIN
  DELETE FROM clouds_pairings
  WHERE status = 'pending' AND expires_at < NOW();
END;
$$ LANGUAGE plpgsql;

-- Cleanup function for expired commands
CREATE OR REPLACE FUNCTION public.cleanup_expired_commands()
RETURNS void AS $$
BEGIN
  DELETE FROM clouds_commands
  WHERE status = 'pending' AND expires_at < NOW();
END;
$$ LANGUAGE plpgsql;

-- Cleanup function for old turns
CREATE OR REPLACE FUNCTION public.cleanup_old_turns()
RETURNS void AS $$
BEGIN
  DELETE FROM clouds_turns
  WHERE created_at < NOW() - INTERVAL '1 hour';
END;
$$ LANGUAGE plpgsql;

-- Cleanup function for old sessions
CREATE OR REPLACE FUNCTION public.cleanup_old_sessions()
RETURNS INTEGER AS $$
DECLARE
    deleted_count INTEGER;
BEGIN
    DELETE FROM auth_tokens
    WHERE last_seen < NOW() - INTERVAL '30 days'
    AND session_id NOT LIKE 'legacy_%';

    GET DIAGNOSTICS deleted_count = ROW_COUNT;

    RETURN deleted_count;
END;
$$ LANGUAGE plpgsql;

-- =============================================================================
-- 10. TRIGGERS
-- =============================================================================

-- Trigger for auth_tokens updated_at
DROP TRIGGER IF EXISTS handle_auth_tokens_updated_at ON public.auth_tokens;
CREATE TRIGGER handle_auth_tokens_updated_at
    BEFORE UPDATE ON public.auth_tokens
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- Trigger for clouds_characters updated_at
DROP TRIGGER IF EXISTS handle_clouds_characters_updated_at ON public.clouds_characters;
CREATE TRIGGER handle_clouds_characters_updated_at
    BEFORE UPDATE ON public.clouds_characters
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- Trigger for pip2_instances updated_at
DROP TRIGGER IF EXISTS update_pip2_instances_updated_at ON public.pip2_instances;
CREATE TRIGGER update_pip2_instances_updated_at
  BEFORE UPDATE ON public.pip2_instances
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- Trigger for guild_command_config updated_at
DROP TRIGGER IF EXISTS update_guild_command_config_updated_at ON public.guild_command_config;
CREATE TRIGGER update_guild_command_config_updated_at
  BEFORE UPDATE ON public.guild_command_config
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- =============================================================================
-- 11. ENABLE REALTIME
-- =============================================================================

-- Enable realtime for tables that need WebSocket subscriptions
ALTER PUBLICATION supabase_realtime ADD TABLE public.clouds_turns;
ALTER PUBLICATION supabase_realtime ADD TABLE public.clouds_commands;
ALTER PUBLICATION supabase_realtime ADD TABLE public.clouds_pairings;

-- =============================================================================
-- MIGRATION COMPLETE
-- =============================================================================
-- Next steps:
-- 1. Create the clouds-assets storage bucket in the Supabase Storage UI
-- 2. Set the bucket to public
-- 3. Deploy your edge functions
-- 4. Update your environment variables with the new Supabase URL and keys
-- =============================================================================
